FROM ubuntu
LABEL mantainer="Yueng De La Hoz <ysdelahoz@gmail.com>"
ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt-get install -y \
	build-essential \
	cmake \
	wget \
	unzip \
	pkg-config \
	libjpeg-dev \
	libpng-dev \
	libtiff-dev \
	libavcodec-dev \
	libavformat-dev \
	libswscale-dev \
	libv4l-dev \
	libxvidcore-dev \
	libx264-dev \
	libgtk-3-dev \
	libatlas-base-dev \
	gfortran \
	python3-dev \
	python3-numpy \
	python3-pip \
	libgstreamer-plugins-base1.0-dev \
	libgstreamer1.0-dev \
	libcanberra-gtk-module

WORKDIR /home/developer
RUN wget -O opencv.zip https://github.com/opencv/opencv/archive/4.5.1.zip
RUN wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.5.1.zip

RUN mkdir -p /usr/local
RUN unzip opencv.zip
RUN unzip opencv_contrib.zip
# Create build directory and switch into it
RUN cd opencv-4.5.1 && \
	mkdir -p build && cd build && \
	cmake -D CMAKE_BUILD_TYPE=RELEASE \ 
	-D CMAKE_INSTALL_PREFIX=/usr/local \
	-D INSTALL_C_EXAMPLES=OFF \
	-D OPENCV_GENERATE_PKGCONFIG=ON \
	-D INSTALL_PYTHON_EXAMPLES=OFF \
	-D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.5.1/modules \
	-D BUILD_EXAMPLES=OFF .. &&\
	cmake --build . &&\
	make -j && \
	make install

RUN rm -rf opencv*
RUN apt -y autoremove
CMD ["bash"]

