# overriding ipython default mode to vi-mode
alias ipython="ipython --TerminalInteractiveShell.editing_mode=vi"
alias pbcopy='xclip -selection clipboard'
alias adb_map_local_network='sudo nmap -p 5555 --open 192.168.86.0/24'

